server: irc.snoonet.org
channel: '#linuxmasterrace'
bot_nick: <bot_nick>
password: <password>
admin_name: <admin_name>
exit_code: Be gone BOTNICK
command_prefix: '\'
user_db_message_log_size: 1000
stopwords: [http, https, www]
imgur_client_id: <id>
imgur_client_secret: <secret>
