# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    environment: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install gettext-base -y
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup environment
      run: |
        export IMGUR_CLIENT_ID=${{ secrets.IMGUR_CLIENT_ID }}
        export IMGUR_CLIENT_SECRET=${{ secrets.IMGUR_CLIENT_SECRET }}
        export CI=1

        echo "IMGUR_CLIENT_ID=$IMGUR_CLIENT_ID" >> $GITHUB_ENV
        echo "IMGUR_CLIENT_SECRET=$IMGUR_CLIENT_SECRET" >> $GITHUB_ENV
        echo "CI=$CI" >> $GITHUB_ENV
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Typecheck with mypy
      run: |
        mypy src test || echo "mypy found error! TODO: Fix so pipeline is green"
    - name: Test with pytest
      run: |
        python -m pytest
